apiVersion: apps/v1
kind: Deployment
metadata:
  name: pract-backend-02-deployment
spec:
  selector:
   matchLabels:
    app: backend-02-jenkins
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-02-jenkins
    spec:
      containers:
        - name: backend-02-jenkins
          image: 'aldavid/azure_pract_1:latest'
          ports:
            - containerPort: 8080
              name: prac-02-port
          imagePullPolicy: Always
          env:
          - name: nombre          
            value: "David"
          - name: TOKEN 
            value: "sp=racwdli&st=2023-04-22T15:46:41Z&se=2023-05-31T23:46:41Z&sv=2021-12-02&sr=c&sig=TX%2B6mbcS7cleToNCJJ8JisyMQ%2BPvCBd1zn5ZnKnsv9w%3D"
          - name: BLOB_URL
            value: "https://aldavid01.blob.core.windows.net/write"
          - name: CONTAINER_NAME
            value: "write"
          
          
---
kind: Service
apiVersion: v1
metadata:
  name: backend-jenkins-svc
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort : 8080
  selector:
   app: backend-02-jenkins


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-02-jenkins-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    nginx.ingress.kubernetes.io/rewrite-target: /
  
spec:
  rules:
  - host: backend-02-jenkins.2b91dc0a09f545d5bdb1.canadaeast.aksapp.io
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: backend-jenkins-svc
            port:
              number: 80
           

  

